// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.158
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebAccessibilityChecker
{
    static class Vsix
    {
        public const string Id = "25a79d25-0fff-4748-afaa-3a67ed116bc9";
        public const string Name = "Web Accessibility Checker";
        public const string Description = "The easiest way to perform accessibility checks on any ASP.NET web application. Fully customizable and support all the major international accessibility standards.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "web, accessibility, a11y, wcag, section 508, wai, asp.net, axe";
    }
}
