// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.158
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebAccessibilityChecker
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "5123051b-3c1d-40e9-aedd-db11ee9f8b9a";
        public const string guidPackageCmdSetString = "762f92d8-926a-4160-8519-badb7cc9a872";
        public const string guidBrowserLinkCmdSetString = "30947ebe-9147-45f9-96cf-401bfc671a82";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
        public static Guid guidBrowserLinkCmdSet = new Guid(guidBrowserLinkCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ErrorListGroup = 0x1000;
        public const int Menu = 0x2000;
        public const int MenuSubGroup = 0x3000;
        public const int MenuSettingsGroup = 0x4000;
        public const int EnableAccessibilityId = 0x0100;
        public const int ClearAllErrors = 0x0200;
        public const int SpecifyRules = 0x0300;
        public const int OpenSettings = 0x0400;
        public const int RunNow = 0x0500;
        public const int IDG_BROWSERLINK_COMMANDS = 0x2001;
    }
}
